# Generated by Django 2.2 on 2023-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=50)),
                ('img', models.ImageField(default='', upload_to='img')),
            ],
        ),
    ]
