# Generated by Django 2.2 on 2023-07-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_pwdlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
    ]
