# Generated by Django 2.2 on 2023-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionP1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=0)),
                ('img', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionP3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=0)),
                ('img', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionP2',
        ),
    ]
