# Generated by Django 4.2.3 on 2024-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20230708_2352"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="QuestionP1",
        ),
        migrations.DeleteModel(
            name="QuestionP2",
        ),
        migrations.DeleteModel(
            name="QuestionP3",
        ),
        migrations.AlterField(
            model_name="pwdlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
